### ISSUE TITLE
Add CI/CD tools

### ISSUE THREAD

**Issue by backlin** [Molmed/emil#5]
I'm upgrading the build pipeline from a collection of bash scripts to `Makefile` and automatic testing and builds.

@johandahlberg Could you check to make sure I am admin on this repo? I can't access the repo settings (the settings tab is not visible).

**Comment by johandahlberg** [comment]
Ok. You should be admin now. Let me know if there are any problems.

**Comment by backlin** [comment]
Yes, thank you!
